server:
  port: [chanege_here]
  error:
    whitelabel:
      enabled: false

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: [chanege_here]
    username: [chanege_here]
    password: [chanege_here]
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none