version: '3'
services:
  mysql:
    image: mysql:8.0
#    volumes:
#      - ./db/conf.d:/etc/mysql/conf.d
#      - ./db/data:/var/lib/mysql
#      - ./db/initdb.d:/docker-entrypoint-initdb.d
#    env_file: .env
    environment:
      MYSQL_DATABASE: lastpunch
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - spring-boot-mysql-network
  auth-server:
    build: ./authServer
    image: sookim1110/auth-server
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/lastpunch?
    depends_on:
      - mysql
    networks:
      - spring-boot-mysql-network
  gateway:
    build: ./gateway
    image: sookim1110/gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
  #  eureka-server:
  #    build: ./eureka-server
  #    image: sookim1110/eureka-server
  #    ports:
  #      - "8761:8761"

networks:
  spring-boot-mysql-network:
    driver: bridge
