version: '3'
services:
  eureka-server:
    image: sookim1110/eureka-server
    ports:
      - "8761:8761"
    networks:
      - lastpunch-network

  redis:
    image: redis
    command: redis-server --port 6379
    ports:
      - 6379:6379
    networks:
      - lastpunch-network

  # mongodb:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - lastpunch-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: lastpunch
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Seoul
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - lastpunch-network

  auth-server:
    image: sookim1110/auth-server2
    ports:
      - "8081:8081"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/lastpunch?
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.mail.username:
      spring.mail.password:
      spring.redis.host: redis
      spring.datasource.username: root
      spring.datasource.password: 1234
    depends_on:
      - mysql
      - redis
      - eureka-server
    restart:
      always
    networks:
      - lastpunch-network

  workspace-server:
    image: njsh4261/workspace-server
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: jdbc:mysql://mysql:3306/lastpunch?
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.username: root
      spring.datasource.password: 1234
    depends_on:
      - mysql
      - eureka-server
    restart:
      always
    networks:
      - lastpunch-network

  # note-server:
  #   image: sookim1110/note-server
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     spring.data.mongodb.uri: mongodb://mongodb:27017/lastpunch
  #     eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
  #   depends_on:
  #     - mongodb
  #     - eureka-server
  #   restart:
  #     always
  #   networks:
  #     - lastpunch-network

  # note-ws-server:
  #   image: sookim1110/note-ws-server
  #   ports:
  #     - "9001:9001"
  #   environment:
  #     spring.redis.host: redis
  #     eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
  #   depends_on:
  #     - redis
  #     - eureka-server
  #   restart:
  #     always
  #   networks:
  #     - lastpunch-network

  gateway:
    image: sookim1110/gateway2
    ports:
      - "8080:8080"
    depends_on:
      - auth-server
      - workspace-server
      - eureka-server
    environment:
      auth.uri: http://auth:8081
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    networks:
      - lastpunch-network


networks:
  lastpunch-network:
    driver: bridge
