server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lastpunch
  application:
    name: presence-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    instance-id: presence-server-instance
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:8761/eureka

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  secret: lastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunch

rabbitmq-stomp:
  host: localhost
  port: 61613
  username: guest
  password: guest
