server:
  port: 8080

eureka:
  instance:
    instance-id: gateway-instance
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:8761/eureka

spring:
  application:
    name: gateway

jwt:
  secret: lastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunch

auth:
  uri: http://auth:8081